"""add something

Revision ID: d48801d755b6
Revises: 20250220_add_stock_code_to_chat
Create Date: 2025-11-25 13:13:33.973324
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd48801d755b6'
down_revision = '20250220_add_stock_code_to_chat'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmark', 'bookmark_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='북마크 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('bookmark', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='북마크 생성자 ID',
               existing_nullable=False)
    op.alter_column('bookmark', 'messages_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='북마크된 메시지 ID',
               existing_nullable=False)
    op.alter_column('bookmark', 'category_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='북마크 카테고리 ID',
               existing_nullable=True)
    op.alter_column('bookmark', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='북마크 생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('bookmark_message'), 'bookmark', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookmark_user_id'), 'bookmark', type_='foreignkey')
    op.create_foreign_key(None, 'bookmark', 'messages', ['messages_id'], ['messages_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'bookmark', 'category', ['category_id'], ['category_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'bookmark', 'users', ['user_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_table_comment(
        'bookmark',
        existing_comment='메시지 북마크 테이블',
        schema=None
    )
    op.alter_column('category', 'category_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='카테고리 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('category', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('category', 'title',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='카테고리 제목',
               existing_nullable=False)
    op.alter_column('category', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='카테고리 생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_category_user_id'), 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'users', ['user_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_table_comment(
        'category',
        existing_comment='북마크 카테고리 테이블',
        schema=None
    )
    op.alter_column('chat', 'chat_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='채팅방 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='채팅방 생성자 ID',
               existing_nullable=False)
    op.alter_column('chat', 'title',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='채팅방 제목',
               existing_nullable=False)
    op.alter_column('chat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='채팅방 생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat', 'lastchat_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='마지막 채팅일시',
               existing_nullable=True)
    op.alter_column('chat', 'trash_can',
               existing_type=postgresql.ENUM('in', 'out', name='trash_enum'),
               comment=None,
               existing_comment='휴지통 상태 (in: 활성, out: 삭제)',
               existing_nullable=True,
               existing_server_default=sa.text("'in'::trash_enum"))
    op.drop_index(op.f('ix_chat_stock_code'), table_name='chat')
    op.create_index(op.f('ix_public_chat_stock_code'), 'chat', ['stock_code'], unique=False, schema='public')
    op.drop_constraint(op.f('user_make_chat'), 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'users', ['user_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_table_comment(
        'chat',
        existing_comment='채팅방 정보 테이블',
        schema=None
    )
    op.drop_constraint(op.f('comments_stock_code_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'stocks', ['stock_code'], ['code'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('financial_statements', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='재무제표 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('financial_statements', 'stock_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='종목 코드 (stocks.code 참조)',
               existing_nullable=False)
    op.alter_column('financial_statements', 'report_period',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='재무제표 기준일 (각 분기말 또는 연말)',
               existing_nullable=False)
    op.alter_column('financial_statements', 'report_type',
               existing_type=postgresql.ENUM('Annual', 'Quarterly', name='report_type_enum'),
               comment=None,
               existing_comment='보고서 유형 (Annual, Quarterly)',
               existing_nullable=False)
    op.alter_column('financial_statements', 'revenue',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='매출액',
               existing_nullable=True)
    op.alter_column('financial_statements', 'operating_income',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='영업이익',
               existing_nullable=True)
    op.alter_column('financial_statements', 'net_income',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='당기순이익',
               existing_nullable=True)
    op.alter_column('financial_statements', 'total_assets',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='자산총계',
               existing_nullable=True)
    op.alter_column('financial_statements', 'total_liabilities',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='부채총계',
               existing_nullable=True)
    op.alter_column('financial_statements', 'total_equity',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='자본총계',
               existing_nullable=True)
    op.alter_column('financial_statements', 'operating_cash_flow',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='영업활동 현금흐름',
               existing_nullable=True)
    op.alter_column('financial_statements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_public_financial_statements_stock_code'), 'financial_statements', ['stock_code'], unique=False, schema='public')
    op.drop_constraint(op.f('financial_statements_stock_code_fkey'), 'financial_statements', type_='foreignkey')
    op.create_foreign_key(None, 'financial_statements', 'stocks', ['stock_code'], ['code'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_table_comment(
        'financial_statements',
        existing_comment='기업 재무제표 (연간/분기별)',
        schema=None
    )
    op.alter_column('messages', 'messages_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='메시지 고유 ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('messages_messages_id_seq'::regclass)"))
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='메시지 작성자 ID',
               existing_nullable=False)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='채팅방 ID',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', name='role_enum'),
               comment=None,
               existing_comment='메시지 역할 (user: 사용자, assistant: AI 어시스턴트)',
               existing_nullable=True,
               existing_server_default=sa.text("'user'::role_enum"))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='메시지 내용',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='메시지 작성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_messages_user_id'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_contain_messages'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'chat', ['chat_id'], ['chat_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_table_comment(
        'messages',
        existing_comment='채팅 메시지 테이블',
        schema=None
    )
    op.alter_column('stocks', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='종목 코드 (PK)',
               existing_nullable=False)
    op.alter_column('stocks', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='회사명 (yfinance: longName)',
               existing_nullable=True)
    op.alter_column('stocks', 'business_summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='기업 개요 (yfinance: longBusinessSummary)',
               existing_nullable=True)
    op.alter_column('stocks', 'market_cap',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='시가총액',
               existing_nullable=True)
    op.alter_column('stocks', 'pe_ratio',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='후행 PER (yfinance: trailingPE)',
               existing_nullable=True)
    op.alter_column('stocks', 'pbr',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='PBR (yfinance: priceToBook)',
               existing_nullable=True)
    op.alter_column('stocks', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='ETL 파이프라인에서 마지막으로 업데이트한 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'stocks',
        existing_comment='주식 기본 정보 및 시장 요약(yfinance .info)',
        schema=None
    )
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='사용자 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'login_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='계정 생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ux_users_login_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['login_id'], schema='public')
    op.drop_table_comment(
        'users',
        existing_comment='사용자 정보 테이블',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        '사용자 정보 테이블',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'users', schema='public', type_='unique')
    op.create_index(op.f('ux_users_login_id'), 'users', ['login_id'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='계정 생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('users', 'login_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               comment='사용자 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'stocks',
        '주식 기본 정보 및 시장 요약(yfinance .info)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('stocks', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='ETL 파이프라인에서 마지막으로 업데이트한 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stocks', 'pbr',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='PBR (yfinance: priceToBook)',
               existing_nullable=True)
    op.alter_column('stocks', 'pe_ratio',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='후행 PER (yfinance: trailingPE)',
               existing_nullable=True)
    op.alter_column('stocks', 'market_cap',
               existing_type=sa.BIGINT(),
               comment='시가총액',
               existing_nullable=True)
    op.alter_column('stocks', 'business_summary',
               existing_type=sa.TEXT(),
               comment='기업 개요 (yfinance: longBusinessSummary)',
               existing_nullable=True)
    op.alter_column('stocks', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='회사명 (yfinance: longName)',
               existing_nullable=True)
    op.alter_column('stocks', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment='종목 코드 (PK)',
               existing_nullable=False)
    op.create_table_comment(
        'messages',
        '채팅 메시지 테이블',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_contain_messages'), 'messages', 'chat', ['chat_id'], ['chat_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_messages_user_id'), 'messages', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='메시지 작성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment='메시지 내용',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', name='role_enum'),
               comment='메시지 역할 (user: 사용자, assistant: AI 어시스턴트)',
               existing_nullable=True,
               existing_server_default=sa.text("'user'::role_enum"))
    op.alter_column('messages', 'chat_id',
               existing_type=sa.INTEGER(),
               comment='채팅방 ID',
               existing_nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               comment='메시지 작성자 ID',
               existing_nullable=False)
    op.alter_column('messages', 'messages_id',
               existing_type=sa.INTEGER(),
               comment='메시지 고유 ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('messages_messages_id_seq'::regclass)"))
    op.create_table_comment(
        'financial_statements',
        '기업 재무제표 (연간/분기별)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'financial_statements', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('financial_statements_stock_code_fkey'), 'financial_statements', 'stocks', ['stock_code'], ['code'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_financial_statements_stock_code'), table_name='financial_statements', schema='public')
    op.alter_column('financial_statements', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('financial_statements', 'operating_cash_flow',
               existing_type=sa.BIGINT(),
               comment='영업활동 현금흐름',
               existing_nullable=True)
    op.alter_column('financial_statements', 'total_equity',
               existing_type=sa.BIGINT(),
               comment='자본총계',
               existing_nullable=True)
    op.alter_column('financial_statements', 'total_liabilities',
               existing_type=sa.BIGINT(),
               comment='부채총계',
               existing_nullable=True)
    op.alter_column('financial_statements', 'total_assets',
               existing_type=sa.BIGINT(),
               comment='자산총계',
               existing_nullable=True)
    op.alter_column('financial_statements', 'net_income',
               existing_type=sa.BIGINT(),
               comment='당기순이익',
               existing_nullable=True)
    op.alter_column('financial_statements', 'operating_income',
               existing_type=sa.BIGINT(),
               comment='영업이익',
               existing_nullable=True)
    op.alter_column('financial_statements', 'revenue',
               existing_type=sa.BIGINT(),
               comment='매출액',
               existing_nullable=True)
    op.alter_column('financial_statements', 'report_type',
               existing_type=postgresql.ENUM('Annual', 'Quarterly', name='report_type_enum'),
               comment='보고서 유형 (Annual, Quarterly)',
               existing_nullable=False)
    op.alter_column('financial_statements', 'report_period',
               existing_type=sa.DATE(),
               comment='재무제표 기준일 (각 분기말 또는 연말)',
               existing_nullable=False)
    op.alter_column('financial_statements', 'stock_code',
               existing_type=sa.VARCHAR(length=20),
               comment='종목 코드 (stocks.code 참조)',
               existing_nullable=False)
    op.alter_column('financial_statements', 'id',
               existing_type=sa.BIGINT(),
               comment='재무제표 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'comments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'comments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('comments_stock_code_fkey'), 'comments', 'stocks', ['stock_code'], ['code'], ondelete='CASCADE')
    op.create_table_comment(
        'chat',
        '채팅방 정보 테이블',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'chat', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('user_make_chat'), 'chat', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_chat_stock_code'), table_name='chat', schema='public')
    op.create_index(op.f('ix_chat_stock_code'), 'chat', ['stock_code'], unique=False)
    op.alter_column('chat', 'trash_can',
               existing_type=postgresql.ENUM('in', 'out', name='trash_enum'),
               comment='휴지통 상태 (in: 활성, out: 삭제)',
               existing_nullable=True,
               existing_server_default=sa.text("'in'::trash_enum"))
    op.alter_column('chat', 'lastchat_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='마지막 채팅일시',
               existing_nullable=True)
    op.alter_column('chat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='채팅방 생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat', 'title',
               existing_type=sa.VARCHAR(length=100),
               comment='채팅방 제목',
               existing_nullable=False)
    op.alter_column('chat', 'user_id',
               existing_type=sa.INTEGER(),
               comment='채팅방 생성자 ID',
               existing_nullable=False)
    op.alter_column('chat', 'chat_id',
               existing_type=sa.INTEGER(),
               comment='채팅방 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'category',
        '북마크 카테고리 테이블',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'category', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_category_user_id'), 'category', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('category', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='카테고리 생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('category', 'title',
               existing_type=sa.VARCHAR(length=50),
               comment='카테고리 제목',
               existing_nullable=False)
    op.alter_column('category', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('category', 'category_id',
               existing_type=sa.INTEGER(),
               comment='카테고리 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'bookmark',
        '메시지 북마크 테이블',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'bookmark', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'bookmark', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'bookmark', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookmark_user_id'), 'bookmark', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bookmark_message'), 'bookmark', 'messages', ['messages_id'], ['messages_id'], ondelete='CASCADE')
    op.alter_column('bookmark', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='북마크 생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookmark', 'category_id',
               existing_type=sa.INTEGER(),
               comment='북마크 카테고리 ID',
               existing_nullable=True)
    op.alter_column('bookmark', 'messages_id',
               existing_type=sa.INTEGER(),
               comment='북마크된 메시지 ID',
               existing_nullable=False)
    op.alter_column('bookmark', 'user_id',
               existing_type=sa.INTEGER(),
               comment='북마크 생성자 ID',
               existing_nullable=False)
    op.alter_column('bookmark', 'bookmark_id',
               existing_type=sa.INTEGER(),
               comment='북마크 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
